const SUPABASE_URL="https://oxlrqzbdwquimvxjvjll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_1IliYfoPR1eoOF5xw6b30g_Wyh-mnO5";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let mode="login",count=0,target=108,mantra="ॐ हनुमते नमः",records=[],sevaRecords=[];
const $=id=>document.getElementById(id); const dateKey=()=>new Date().toLocaleDateString('en-CA');
const thoughts=["Naam Smaran is a practice of remembrance, not a race.","A small sincere practice can be more sustainable than a large forced target.","Let the mantra bring attention, steadiness and gratitude.","Seva can be simple: help, share, listen, clean or care."];
function render(){const saved=records.find(r=>r.recorded_date===dateKey());const total=records.reduce((s,r)=>s+Number(r.jaap_count||0),0);const completed=new Set(records.filter(r=>r.completed).map(r=>r.recorded_date));let streak=0,d=new Date();while(completed.has(d.toLocaleDateString('en-CA'))){streak++;d.setDate(d.getDate()-1)}
const sevaCount=sevaRecords.length; ["homeJaap","totalJaap"].forEach(id=>$(id).textContent=total.toLocaleString()); ["homeStreak","streak"].forEach(id=>$(id).textContent=streak); ["homeSeva","seva"].forEach(id=>$(id).textContent=sevaCount); $("count").textContent=count.toLocaleString();$("targetText").textContent=Number(target).toLocaleString();$("completeMsg").textContent=count>=target?"🙏 आज की साधना पूर्ण! 🚩":""; const pct=Math.min(100,(count/target)*100);$("jaapProgress").style.width=pct+"%";$("homeProgress").style.width=pct+"%";$("homeTargetText").textContent=`Your daily target is ${Number(target).toLocaleString()} jaap.`;$("savedToday").textContent=saved?`${Number(saved.jaap_count).toLocaleString()} jaap saved for ${saved.mantra}.` : "No saved record yet.";
const b=[]; if(total>=108)b.push("📿 First 108 Jaap");if(total>=1008)b.push("🚩 1,008 Jaap");if(total>=10000)b.push("🏅 10,000 Jaap");if(total>=100000)b.push("🌟 1 Lakh Jaap");if(streak>=7)b.push("🔥 7-Day Consistency");if(streak>=21)b.push("🌺 21-Day Consistency");if(sevaCount>=1)b.push("❤️ First Seva");if(sevaCount>=10)b.push("🪔 10 Seva Activities");$("badges").innerHTML=b.length?b.map(x=>`<span class="badge">${x}</span>`).join(" "):"Start your journey today. 🙏";
$("history").innerHTML=records.slice().sort((a,b)=>b.recorded_date.localeCompare(a.recorded_date)).slice(0,14).map(r=>`<div class="history-row"><span>${r.recorded_date}</span><b>${Number(r.jaap_count).toLocaleString()}</b><span>${r.completed?"✅":"—"}</span></div>`).join("")||"No saved practice yet."; $("dailyThought").textContent=thoughts[new Date().getDate()%thoughts.length];
}
function page(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));$(p).classList.add('active');const b=document.querySelector(`[data-page="${p}"]`);if(b)b.classList.add('active');}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
$("plus").onclick=()=>{count++;render()};$("minus").onclick=()=>{count=Math.max(0,count-1);render()};$("mala").onclick=()=>{count+=108;render()};$("reset").onclick=()=>{count=0;render()};
$("mantra").onchange=e=>mantra=e.target.value;
$("target").onchange=e=>{if(e.target.value==='custom'){$("customTarget").classList.remove('hidden');return}$('customTarget').classList.add('hidden');target=+e.target.value;count=0;render()};
$("customTarget").onchange=e=>{const v=Math.max(1,Math.min(1000000,Number(e.target.value)||108));target=v;count=0;render()};
function setMode(m){mode=m;$("loginTab").classList.toggle('active',m==='login');$("signupTab").classList.toggle('active',m==='signup');$("nameWrap").classList.toggle('hidden',m!=='signup');$("authSubmit").textContent=m==='login'?'Login':'Create account';$("authMessage").textContent=''}
$("loginTab").onclick=()=>setMode('login');$("signupTab").onclick=()=>setMode('signup');
async function ensureProfile(user,name){const r=await sb.from('profiles').upsert({id:user.id,display_name:name||'Devotee'},{onConflict:'id'});if(r.error)console.error(r.error)}
async function load(){const {data:{user}}=await sb.auth.getUser();if(!user)return;await ensureProfile(user);const p=await sb.from('profiles').select('display_name').eq('id',user.id).maybeSingle();const jr=await sb.from('jaap_records').select('user_id,mantra,jaap_count,target,completed,recorded_date').eq('user_id',user.id).order('recorded_date',{ascending:false});const sr=await sb.from('seva_records').select('id,seva_type,note,recorded_date').eq('user_id',user.id).order('recorded_date',{ascending:false});if(jr.error)console.error(jr.error);if(sr.error)console.error(sr.error);records=jr.data||[];sevaRecords=sr.data||[];if(p.data){$('profileName').textContent=p.data.display_name||'Devotee';$('welcome').textContent=`Welcome, ${p.data.display_name||'Devotee'} 🙏`}$('profileEmail').textContent=user.email||'';const saved=records.find(r=>r.recorded_date===dateKey());if(saved){count=Number(saved.jaap_count)||0;target=Number(saved.target)||108;mantra=saved.mantra||mantra;$('target').value=['108','216','500','1008'].includes(String(target))?String(target):'custom';if($('target').value==='custom'){$('customTarget').classList.remove('hidden');$('customTarget').value=target}$('mantra').value=mantra}render()}
$("authForm").onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='Working…';const email=$('email').value.trim(),password=$('password').value;if(mode==='signup'){const r=await sb.auth.signUp({email,password});if(r.error){$('authMessage').textContent=r.error.message;return}if(r.data.user)await ensureProfile(r.data.user,$('displayName').value.trim());$('authMessage').textContent='Account created. Check your email if confirmation is enabled, then log in.'}else{const r=await sb.auth.signInWithPassword({email,password});if(r.error){$('authMessage').textContent=r.error.message;return}await show()}};
async function show(){$('auth').classList.add('hidden');$('app').classList.remove('hidden');await load()}
$("saveJaap").onclick=async()=>{const {data:{user}}=await sb.auth.getUser();if(!user)return;$('saveMessage').textContent='Saving…';const payload={user_id:user.id,mantra,jaap_count:count,target,completed:count>=target,recorded_date:dateKey()};const r=await sb.from('jaap_records').upsert(payload,{onConflict:'user_id,recorded_date'}).select().single();if(r.error){$('saveMessage').textContent=r.error.message;return}records=[r.data,...records.filter(x=>x.recorded_date!==dateKey())];$('saveMessage').textContent='☁️ Today\'s jaap saved.';render()};
$("sevaForm").onsubmit=async e=>{e.preventDefault();const {data:{user}}=await sb.auth.getUser();if(!user)return;$('sevaMessage').textContent='Saving…';const r=await sb.from('seva_records').insert({user_id:user.id,seva_type:$('sevaType').value,note:$('sevaNote').value.trim()}).select().single();if(r.error){$('sevaMessage').textContent=r.error.message;return}sevaRecords.unshift(r.data);$('sevaNote').value='';$('sevaMessage').textContent='❤️ Seva recorded. Thank you.';render()};
$("logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
(async()=>{setMode('login');const r=await sb.auth.getSession();if(r.data.session)await show();else $('auth').classList.remove('hidden');render()})();
